<?php 
function get_product($product=null){
  $row['sku'] = $product->getSku();
  $row['title'] = $product->getName();
  $row['category'] = array_shift($product->getCategoryIds());
  $row['description'] = $product->getDescription();
  $row['units'] = 'stk.'; //not implemented
  $row['price'] = $product->getFinalPrice();
  return $row;
}

function export_products(){
  $data = array();
  $products = Mage::getModel('catalog/product')->getCollection();
  foreach($products as $product){
    $data[] = get_product($product->load());
  }
  return $data;
}

function get_customer($customer){
  $ids = $customer->getPrimaryAddressIds();
  $address = Mage::getModel('customer/address')->load(array_shift($ids));
  $row['id'] = $customer['entity_id'];
  $row['company'] = '';
  $row['lastname'] = $customer->getLastname();
  $row['firstname'] = $customer->getFirstname();
  $row['middlename'] = $customer->getMiddlename();
  $row['phone'] = $address->getTelephone();
  $row['address1'] = $address->getStreet1();
  $row['address2'] = $address->getStreet2();
  $row['city'] = $address->getCity();
  $row['country'] = $address->getCountry();
  $row['postalcode'] = $address->getPostcode();
  $row['email'] = $customer->getEmail();

  return $row;
}

function export_customers(){
  $data = array();
  $customers = Mage::getModel('customer/customer')->getCollection();
  foreach($customers as $customer){
    $data[] = get_customer($customer->load());
  }
  return $data;
}

function get_order($order) {

  $row['orderid'] = $order->getEntityId() ;
  $row['customerid'] = $order->getCustomerId();
  $row['number'] = '';
  $row['total'] = $order->getGrandTotal();
  $row['subtotal'] = $order->getSubtotal();
  $row['tax'] = $order->getTaxAmount();
  $row['shipping'] = $order->getShippingAmount();
  $row['shipping_tax'] = $order->getShippingTaxAmount();
  $row[] = '';
  $row['coupon_code'] = $order->getCouponCode();
  $row['discount'] = $order->getDiscountAmount();
  $row['currency'] = $order->getOrderCurrencyCode();
  $row['shipping_method'] = $order->getShippingMethod();
  $row['date'] = $order->getCreatedAt();
  $row[] = '';
  $customer =
  get_customer(Mage::getModel('customer/customer')->load($order->getCustomerId()));
  
  $row['phone'] = $customer['phone'];
  return $row;
}

function get_product_line($order_line) {
  $row['orderid'] = $order_line->getOrderId();
  $row['sku'] = $order_line->getSku();
  $row['title'] = $order_line->getName();
  $row['quantity'] = $order_line->getQtyToInvoice();
  $row['price'] = floatval($order_line->getPrice());
  $row['attribute'] = '';
  return $row;
}

function export_orders(){
  $data = array();
  $orders = Mage::getModel('sales/order')->getCollection();
  foreach($orders as $order){
    $loaded_order = $order->load();
    $data[] = get_order($loaded_order);
    $items = $loaded_order->getAllItems();
    foreach($items as $item){
      $data[] = get_product_line($item);
    }
  }
  return $data;
}

function import_product($product_data){
  $product =
  Mage::getModel('catalog/product')->load($product_data['Number']);

  $product->setWebsiteIds(array(1));
  $product->setAttributeSetId(4);
  $product->setSku($product_data['Number']);
  $product->setName($product_data['Name']);
  $product->setDescription($product_data['Description']);
  $product->setShortDescription($product_data['Description']);
  $product->setTypeId('simple');
  $product->setWeight(0);
  $product->setCategoryIds(array($product_data['ProductGroup']));
  $product->setPrice($product_data['SalesPrice']);
  $product->setCost($product_data['CostPrice']);
  $product->setTaxClassId('2');
  $product->setStatus(1);
  $product->setCreatedAt(strtotime('now'));

  $product->save();
}

function output_data($data){
  switch($format){
    case 'csv':
    default:
      $fh = fopen('php://output','w');
      foreach($data as $line){
        fputcsv($fh,$line,';','"');
      }
      fclose($fh);
    break;
  }
}

$type = $_GET['type'];
$action = $_GET['action'];
$key = $_GET['key'];

if($key == ''){
  if($action) {
    import_product($_POST);
  } else {
    switch($type){
      case 'orders':
        $data = export_orders();
      break;
      case 'products':
        $data = export_products();
      break;
      case 'customers':
        $data = export_customers();
      break;
      default:
        die('The action chosen is not defined');
    }
    if(!empty($data)){
      output_data($data);
    } else {
      die('An error occured, no data was found');
    }
  }
} else {
  die('Access denied');
}
?>
